FROM nvcr.io/nvidia/l4t-base:r32.5.0

# OS/Version (FILE): cat /etc/issue.net
ARG DEBIAN_FRONTEND=noninteractive

# System update
RUN apt-get clean && apt-get update && apt-get install -y --no-install-recommends\
        build-essential \
        cmake \
        git \
        wget \
        unzip \
        yasm \
        pkg-config \
        libtool \
        nasm \
        automake \
        libpng-dev \
        libjpeg-turbo8-dev \
        libssl-dev \
        liblapack-dev \
        libatlas-base-dev \
        python3.7 \
        python3.7-dev \
        python3-distutils \
        libpython3-dev \
        python3-pip \
        python3-numpy \
        libeigen3-dev \
        libjpeg-dev \
        python3-setuptools \
	libxmu-dev \
	libxi-dev \
        python3-zmq \
        python3-protobuf \
        gnupg1 gnupg2 \
	libgtk-3-dev \
    	libavcodec-dev \
	libavformat-dev \
	libswscale-dev \
	libv4l-dev \
	libxvidcore-dev \
	libx264-dev \
	libtiff-dev \
 && rm -rf /var/lib/apt/lists/*

COPY ./trusted.gpg /etc/apt/
COPY ./jetson-ota-public.asc /etc/apt/trusted.gpg.d/
RUN apt-key add /etc/apt/trusted.gpg && apt-key add /etc/apt/trusted.gpg.d/jetson-ota-public.asc
COPY ./nvidia-l4t-apt-source.list /etc/apt/sources.list.d/

RUN apt-get clean && apt-get update && apt upgrade -y && apt-get install -y --no-install-recommends\
	libcudnn8 \
	libcudnn8-dev \
	libcublas-dev \
	cuda-cufft-dev-10-0 \
    cuda-npp-dev-10-0 \
    cuda-nvcc-10-0 \
    libcublas-dev \
    cuda-compiler-10-0 \
    cuda-cudart-dev-10-0 \
    cuda-cupti-dev-10-0 \
    cuda-curand-dev-10-0 \
    cuda-cusolver-dev-10-0 \
    cuda-cusparse-dev-10-0 \
    cuda-libraries-dev-10-0 \
    cuda-misc-headers-10-0 \
    cuda-nvml-dev-10-0

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10

#Getting OpenCV
RUN mkdir /opencv_build
WORKDIR  /opencv_build
RUN git clone https://github.com/opencv/opencv.git

#Compiling OpenCV
RUN mkdir /opencv_build/opencv/build
WORKDIR  /opencv_build/opencv/build
RUN cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D INSTALL_C_EXAMPLES=ON \
    -D INSTALL_PYTHON_EXAMPLES=ON \
    -D OPENCV_GENERATE_PKGCONFIG=ON \
    -D BUILD_EXAMPLES=ON ..

RUN make -j$(cat /proc/cpuinfo | grep processor | wc -l)
RUN make install




#Compiling Darknet (You Need to Run this make inside the docker since the build needs NVIDIA GPU which is only possible by passing --runtime=nvidia)
#docker run -it --runtime=nvidia docker-darknet_yolo:latest
#RUN make
